language: ruby
rvm: # http://rubies.travis-ci.org/
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
env:
  - WITH_LIBXML=true
  - WITH_LIBXML=false
before_script: |
  if [ "$WITH_LIBXML" == "false" ]; then
    sudo apt-get remove libxml2-dev
  fi
